# This file was generated by the gen_go_makefile script.
# Makefile for the ask-ai project.

PROJECT_NAME := ask-ai

SRC_FILES := $(wildcard *.go)
BIN_FILES := $(patsubst %.go,bin/%,$(SRC_FILES))
PKG_FILES := $(wildcard llm/*.go)
TST_FILES := $(wildcard test/*.go)

GO := go

# GOFLAGS := -asm
TESTFLAGS := -v -cover -coverprofile=coverage.out

# all: build test run

clean:
	rm -f bin/*

test: $(TST_FILES)
	$(GO) test $(TESTFLAGS) ./test || exit 1

build: $(BIN_FILEs) $(PKG_FILES)
	$(GO) build $(GOFLAGS) -o bin/$(PROJECT_NAME) main.go

run: $(BIN_FILES)
	./bin/$(PROJECT_NAME)

bin/%: src/%.go
	$(GO) build $(GOFLAGS) -o $@ $<
